project:
  type: website

website:
  title: "Livre de recettes"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: soumettre.qmd
        text: Soumettre une recette
  sidebar:
    style: docked
    search: true
    contents: recettes
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
