project:
  type: website

website:
  title: "Livre de recettes"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
  sidebar:
    style: docked
    search: true
    contents:
      - section: Desserts
        contents:
          - recettes/brioche-a-la-cannelle-et-pomme-de-terre.qmd
      - section: Salades
        contents:
          - recettes/salade-de-legumineuses.qmd
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
