project:
  type: website

website:
  back-to-top-navigation: true
  title: "Nos Recettes"
  page-footer: "Livre de recettes de Mme et M."
  navbar:
    left:
      - href: index.qmd
        text: Accueil
  sidebar:
    style: docked
    search: true
    contents: recettes

format:
  html:
    theme:
      light: litera
      dark: superhero
    css: styles.css
    toc: true
    respect-user-color-scheme: true
