project:
  type: website

website:
  title: "recettes2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: docked
    search: true
    contents:
      - section: Desserts
        contents:
          - recettes/brioche.qmd
format:
  html:
    theme:
      - vapor
      - brand
    css: styles.css
    toc: true
