project:
  type: website

website:
  title: "Live de recettes"
  navbar:
    left:
      - href: index.qmd
        text: Accueil

format:
  html:
    theme:
      - vapor
      - brand
    css: styles.css
    toc: true
