project:
  type: website

lang: fr

website:
  back-to-top-navigation: true
  title: "Nos Recettes"
  page-footer: "Livre de recettes de Mme et M."

  navbar:
    background: primary
    left:
      - href: recettes/accompagnements/index.qmd
        text: Accompagnements
      - href: recettes/repas/index.qmd
        text: Repas
      - href: recettes/desserts/index.qmd
        text: Desserts
      - href: soumettre.qmd
        text: Soumettre une recette
    style: docked
    search: true

format:
  html:
    theme:
      light: litera
      dark: superhero
    css: styles.css
    toc: true
    respect-user-color-scheme: true
